spring.application.name=CollageManagementSyatem
SPRING_DATASOURCE_URL=jdbc:mysql://your-db-host:3306/dbname
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=yourpassword
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port=${PORT:8080}
